version: '3.7'

services:
 src:
   build:
     context: .
   ports:
     - "8000:8000"
   volumes:
     - ./src:/src
   command: >
     sh -c "echo goto dev server at: http://127.0.0.1:8000/ &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"